name: Fetch token details hourly

on:
  schedule:
    - cron: '0 * * * *'  # top of every hour (UTC)
  workflow_dispatch:

jobs:
  fetch:
    runs-on: ubuntu-latest
    env:
      HYPESCORE_API_KEY: ${{ secrets.HYPESCORE_API_KEY }}
      MONGO_URI: ${{ secrets.MONGO_URI }}
      ADDRESSES: ${{ secrets.ADDRESSES }}
      MONGO_DB: lapis_develop
      MONGO_COLLECTION: Token
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10.18'

      - name: Install deps
        run: python -m pip install --upgrade pip && pip install -r requirements.txt

      - name: Run fetch script
        run: python get.py
